# ==========================================================================
# CRE WORKFLOW SETTINGS FILE — Price Scanner
# ==========================================================================

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "price-scanner-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"

# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "price-scanner-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"
