/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type AgentConfigStruct = {agentId: BigNumberish, owner: AddressLike, productCategories: string[], minOrderSize: BigNumberish, maxOrderSize: BigNumberish, active: boolean, createdAt: BigNumberish, totalDeals: BigNumberish, totalVolume: BigNumberish, successRate: BigNumberish}

    export type AgentConfigStructOutput = [agentId: bigint, owner: string, productCategories: string[], minOrderSize: bigint, maxOrderSize: bigint, active: boolean, createdAt: bigint, totalDeals: bigint, totalVolume: bigint, successRate: bigint] & {agentId: bigint, owner: string, productCategories: string[], minOrderSize: bigint, maxOrderSize: bigint, active: boolean, createdAt: bigint, totalDeals: bigint, totalVolume: bigint, successRate: bigint }
  

  export interface AgentRegistryInterface extends Interface {
    getFunction(nameOrSignature: "MAX_AGENTS_BUSINESS" | "MAX_AGENTS_FREE" | "MAX_AGENTS_PRO" | "MAX_CATEGORIES_PER_AGENT" | "acceptAdmin" | "admin" | "authorizedUpdaters" | "batchSetUserTier" | "createAgent" | "deactivateAgent" | "getAgent" | "getAgentOwner" | "getAgentStats" | "getAgentsByOwner" | "isAgentActive" | "nextAgentId" | "ownerAgents" | "pendingAdmin" | "reactivateAgent" | "recordDealCompletion" | "setAuthorizedUpdater" | "setUserTier" | "transferAdmin" | "updateCategories" | "updateOrderLimits" | "userTier"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgentCreated" | "AgentDeactivated" | "AgentReactivated" | "AgentStatsUpdated" | "AgentUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_AGENTS_BUSINESS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_AGENTS_FREE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_AGENTS_PRO', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CATEGORIES_PER_AGENT', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedUpdaters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'batchSetUserTier', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'createAgent', values: [string[], BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'deactivateAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgentOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgentStats', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAgentsByOwner', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAgentActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextAgentId', values?: undefined): string;
encodeFunctionData(functionFragment: 'ownerAgents', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pendingAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'reactivateAgent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'recordDealCompletion', values: [BigNumberish, BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'setAuthorizedUpdater', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setUserTier', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateCategories', values: [BigNumberish, string[]]): string;
encodeFunctionData(functionFragment: 'updateOrderLimits', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'userTier', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_AGENTS_BUSINESS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_AGENTS_FREE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_AGENTS_PRO', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CATEGORIES_PER_AGENT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedUpdaters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchSetUserTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deactivateAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentStats', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAgentsByOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAgentActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextAgentId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerAgents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reactivateAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordDealCompletion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedUpdater', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUserTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCategories', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateOrderLimits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userTier', data: BytesLike): Result;
  }

  
    export namespace AgentCreatedEvent {
      export type InputTuple = [agentId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [agentId: bigint, owner: string];
      export interface OutputObject {agentId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentDeactivatedEvent {
      export type InputTuple = [agentId: BigNumberish];
      export type OutputTuple = [agentId: bigint];
      export interface OutputObject {agentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentReactivatedEvent {
      export type InputTuple = [agentId: BigNumberish];
      export type OutputTuple = [agentId: bigint];
      export interface OutputObject {agentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentStatsUpdatedEvent {
      export type InputTuple = [agentId: BigNumberish, totalDeals: BigNumberish, totalVolume: BigNumberish, successRate: BigNumberish];
      export type OutputTuple = [agentId: bigint, totalDeals: bigint, totalVolume: bigint, successRate: bigint];
      export interface OutputObject {agentId: bigint, totalDeals: bigint, totalVolume: bigint, successRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentUpdatedEvent {
      export type InputTuple = [agentId: BigNumberish];
      export type OutputTuple = [agentId: bigint];
      export interface OutputObject {agentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: AgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_AGENTS_BUSINESS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_AGENTS_FREE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_AGENTS_PRO: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_CATEGORIES_PER_AGENT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptAdmin: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authorizedUpdaters: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    batchSetUserTier: TypedContractMethod<
      [users: AddressLike[], tiers: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    createAgent: TypedContractMethod<
      [categories: string[], minOrderSize: BigNumberish, maxOrderSize: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    deactivateAgent: TypedContractMethod<
      [agentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAgent: TypedContractMethod<
      [agentId: BigNumberish, ],
      [[AgentConfigStructOutput, string[]] & {config: AgentConfigStructOutput, categories: string[] }],
      'view'
    >
    

    
    getAgentOwner: TypedContractMethod<
      [agentId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getAgentStats: TypedContractMethod<
      [agentId: BigNumberish, ],
      [[bigint, bigint, bigint] & {totalDeals: bigint, totalVolume: bigint, successRate: bigint }],
      'view'
    >
    

    
    getAgentsByOwner: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    isAgentActive: TypedContractMethod<
      [agentId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    nextAgentId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ownerAgents: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    pendingAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reactivateAgent: TypedContractMethod<
      [agentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    recordDealCompletion: TypedContractMethod<
      [agentId: BigNumberish, volume: BigNumberish, success: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedUpdater: TypedContractMethod<
      [updater: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setUserTier: TypedContractMethod<
      [user: AddressLike, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateCategories: TypedContractMethod<
      [agentId: BigNumberish, categories: string[], ],
      [void],
      'nonpayable'
    >
    

    
    updateOrderLimits: TypedContractMethod<
      [agentId: BigNumberish, minOrderSize: BigNumberish, maxOrderSize: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    userTier: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_AGENTS_BUSINESS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_AGENTS_FREE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_AGENTS_PRO'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CATEGORIES_PER_AGENT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptAdmin'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedUpdaters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'batchSetUserTier'): TypedContractMethod<
      [users: AddressLike[], tiers: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createAgent'): TypedContractMethod<
      [categories: string[], minOrderSize: BigNumberish, maxOrderSize: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deactivateAgent'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAgent'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [[AgentConfigStructOutput, string[]] & {config: AgentConfigStructOutput, categories: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentOwner'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentStats'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [[bigint, bigint, bigint] & {totalDeals: bigint, totalVolume: bigint, successRate: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getAgentsByOwner'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'isAgentActive'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextAgentId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ownerAgents'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reactivateAgent'): TypedContractMethod<
      [agentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'recordDealCompletion'): TypedContractMethod<
      [agentId: BigNumberish, volume: BigNumberish, success: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedUpdater'): TypedContractMethod<
      [updater: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUserTier'): TypedContractMethod<
      [user: AddressLike, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCategories'): TypedContractMethod<
      [agentId: BigNumberish, categories: string[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateOrderLimits'): TypedContractMethod<
      [agentId: BigNumberish, minOrderSize: BigNumberish, maxOrderSize: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userTier'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'AgentCreated'): TypedContractEvent<AgentCreatedEvent.InputTuple, AgentCreatedEvent.OutputTuple, AgentCreatedEvent.OutputObject>;
getEvent(key: 'AgentDeactivated'): TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
getEvent(key: 'AgentReactivated'): TypedContractEvent<AgentReactivatedEvent.InputTuple, AgentReactivatedEvent.OutputTuple, AgentReactivatedEvent.OutputObject>;
getEvent(key: 'AgentStatsUpdated'): TypedContractEvent<AgentStatsUpdatedEvent.InputTuple, AgentStatsUpdatedEvent.OutputTuple, AgentStatsUpdatedEvent.OutputObject>;
getEvent(key: 'AgentUpdated'): TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentCreated(uint256,address)': TypedContractEvent<AgentCreatedEvent.InputTuple, AgentCreatedEvent.OutputTuple, AgentCreatedEvent.OutputObject>;
      AgentCreated: TypedContractEvent<AgentCreatedEvent.InputTuple, AgentCreatedEvent.OutputTuple, AgentCreatedEvent.OutputObject>;
    

      'AgentDeactivated(uint256)': TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
      AgentDeactivated: TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
    

      'AgentReactivated(uint256)': TypedContractEvent<AgentReactivatedEvent.InputTuple, AgentReactivatedEvent.OutputTuple, AgentReactivatedEvent.OutputObject>;
      AgentReactivated: TypedContractEvent<AgentReactivatedEvent.InputTuple, AgentReactivatedEvent.OutputTuple, AgentReactivatedEvent.OutputObject>;
    

      'AgentStatsUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<AgentStatsUpdatedEvent.InputTuple, AgentStatsUpdatedEvent.OutputTuple, AgentStatsUpdatedEvent.OutputObject>;
      AgentStatsUpdated: TypedContractEvent<AgentStatsUpdatedEvent.InputTuple, AgentStatsUpdatedEvent.OutputTuple, AgentStatsUpdatedEvent.OutputObject>;
    

      'AgentUpdated(uint256)': TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
      AgentUpdated: TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
    
    };
  }