/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type DisputeStruct = {disputeId: BigNumberish, dealId: BigNumberish, filedBy: AddressLike, reason: string, filedAt: BigNumberish, supplierDeadline: BigNumberish, status: BigNumberish, outcome: BigNumberish, buyerRefundBps: BigNumberish}

    export type DisputeStructOutput = [disputeId: bigint, dealId: bigint, filedBy: string, reason: string, filedAt: bigint, supplierDeadline: bigint, status: bigint, outcome: bigint, buyerRefundBps: bigint] & {disputeId: bigint, dealId: bigint, filedBy: string, reason: string, filedAt: bigint, supplierDeadline: bigint, status: bigint, outcome: bigint, buyerRefundBps: bigint }
  

  export interface DisputeResolverInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "DISPUTE_FEE" | "SUPPLIER_RESPONSE_PERIOD" | "acceptAdmin" | "admin" | "arbitrators" | "dealDisputeId" | "disputes" | "escrowVault" | "expireDispute" | "feeDepositor" | "fileDispute" | "getDispute" | "getDisputeByDeal" | "getSupplierResponse" | "isDisputeExpirable" | "nextDisputeId" | "pendingAdmin" | "resolveDispute" | "setArbitrator" | "setEscrowVault" | "supplierRespond" | "supplierResponses" | "transferAdmin" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeExpired" | "DisputeFeeRefunded" | "DisputeFiled" | "DisputeResolved" | "SupplierResponded"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'DISPUTE_FEE', values?: undefined): string;
encodeFunctionData(functionFragment: 'SUPPLIER_RESPONSE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'arbitrators', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'dealDisputeId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'disputes', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowVault', values?: undefined): string;
encodeFunctionData(functionFragment: 'expireDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeDepositor', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'fileDispute', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDisputeByDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSupplierResponse', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isDisputeExpirable', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextDisputeId', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setArbitrator', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setEscrowVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'supplierRespond', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'supplierResponses', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DISPUTE_FEE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SUPPLIER_RESPONSE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'arbitrators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dealDisputeId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expireDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeDepositor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fileDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDisputeByDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSupplierResponse', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDisputeExpirable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextDisputeId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setArbitrator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setEscrowVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supplierRespond', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supplierResponses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace DisputeExpiredEvent {
      export type InputTuple = [disputeId: BigNumberish];
      export type OutputTuple = [disputeId: bigint];
      export interface OutputObject {disputeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeFeeRefundedEvent {
      export type InputTuple = [disputeId: BigNumberish, to: AddressLike];
      export type OutputTuple = [disputeId: bigint, to: string];
      export interface OutputObject {disputeId: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeFiledEvent {
      export type InputTuple = [disputeId: BigNumberish, dealId: BigNumberish, filedBy: AddressLike];
      export type OutputTuple = [disputeId: bigint, dealId: bigint, filedBy: string];
      export interface OutputObject {disputeId: bigint, dealId: bigint, filedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [disputeId: BigNumberish, outcome: BigNumberish, buyerRefundBps: BigNumberish];
      export type OutputTuple = [disputeId: bigint, outcome: bigint, buyerRefundBps: bigint];
      export interface OutputObject {disputeId: bigint, outcome: bigint, buyerRefundBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplierRespondedEvent {
      export type InputTuple = [disputeId: BigNumberish, response: string];
      export type OutputTuple = [disputeId: bigint, response: string];
      export interface OutputObject {disputeId: bigint, response: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface DisputeResolver extends BaseContract {
    
    connect(runner?: ContractRunner | null): DisputeResolver;
    waitForDeployment(): Promise<this>;

    interface: DisputeResolverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DISPUTE_FEE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SUPPLIER_RESPONSE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptAdmin: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    arbitrators: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    dealDisputeId: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    disputes: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {disputeId: bigint, dealId: bigint, filedBy: string, reason: string, filedAt: bigint, supplierDeadline: bigint, status: bigint, outcome: bigint, buyerRefundBps: bigint }],
      'view'
    >
    

    
    escrowVault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    expireDispute: TypedContractMethod<
      [disputeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeDepositor: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    fileDispute: TypedContractMethod<
      [dealId: BigNumberish, reason: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    getDispute: TypedContractMethod<
      [disputeId: BigNumberish, ],
      [DisputeStructOutput],
      'view'
    >
    

    
    getDisputeByDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [DisputeStructOutput],
      'view'
    >
    

    
    getSupplierResponse: TypedContractMethod<
      [disputeId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    isDisputeExpirable: TypedContractMethod<
      [disputeId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    nextDisputeId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveDispute: TypedContractMethod<
      [disputeId: BigNumberish, buyerRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setArbitrator: TypedContractMethod<
      [arb: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setEscrowVault: TypedContractMethod<
      [_vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supplierRespond: TypedContractMethod<
      [disputeId: BigNumberish, response: string, ],
      [void],
      'nonpayable'
    >
    

    
    supplierResponses: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DISPUTE_FEE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SUPPLIER_RESPONSE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptAdmin'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'arbitrators'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'dealDisputeId'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disputes'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {disputeId: bigint, dealId: bigint, filedBy: string, reason: string, filedAt: bigint, supplierDeadline: bigint, status: bigint, outcome: bigint, buyerRefundBps: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'escrowVault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'expireDispute'): TypedContractMethod<
      [disputeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeDepositor'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'fileDispute'): TypedContractMethod<
      [dealId: BigNumberish, reason: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getDispute'): TypedContractMethod<
      [disputeId: BigNumberish, ],
      [DisputeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDisputeByDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [DisputeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getSupplierResponse'): TypedContractMethod<
      [disputeId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isDisputeExpirable'): TypedContractMethod<
      [disputeId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nextDisputeId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [disputeId: BigNumberish, buyerRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setArbitrator'): TypedContractMethod<
      [arb: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setEscrowVault'): TypedContractMethod<
      [_vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supplierRespond'): TypedContractMethod<
      [disputeId: BigNumberish, response: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supplierResponses'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'DisputeExpired'): TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
getEvent(key: 'DisputeFeeRefunded'): TypedContractEvent<DisputeFeeRefundedEvent.InputTuple, DisputeFeeRefundedEvent.OutputTuple, DisputeFeeRefundedEvent.OutputObject>;
getEvent(key: 'DisputeFiled'): TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'SupplierResponded'): TypedContractEvent<SupplierRespondedEvent.InputTuple, SupplierRespondedEvent.OutputTuple, SupplierRespondedEvent.OutputObject>;

    filters: {
      
      'DisputeExpired(uint256)': TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
      DisputeExpired: TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
    

      'DisputeFeeRefunded(uint256,address)': TypedContractEvent<DisputeFeeRefundedEvent.InputTuple, DisputeFeeRefundedEvent.OutputTuple, DisputeFeeRefundedEvent.OutputObject>;
      DisputeFeeRefunded: TypedContractEvent<DisputeFeeRefundedEvent.InputTuple, DisputeFeeRefundedEvent.OutputTuple, DisputeFeeRefundedEvent.OutputObject>;
    

      'DisputeFiled(uint256,uint256,address)': TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
      DisputeFiled: TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
    

      'DisputeResolved(uint256,uint8,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'SupplierResponded(uint256,string)': TypedContractEvent<SupplierRespondedEvent.InputTuple, SupplierRespondedEvent.OutputTuple, SupplierRespondedEvent.OutputObject>;
      SupplierResponded: TypedContractEvent<SupplierRespondedEvent.InputTuple, SupplierRespondedEvent.OutputTuple, SupplierRespondedEvent.OutputObject>;
    
    };
  }