/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type DealStruct = {dealId: BigNumberish, agentId: BigNumberish, buyer: AddressLike, supplier: AddressLike, amount: BigNumberish, platformFee: BigNumberish, createdAt: BigNumberish, deliveryDeadline: BigNumberish, status: BigNumberish, metadataURI: string}

    export type DealStructOutput = [dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint, platformFee: bigint, createdAt: bigint, deliveryDeadline: bigint, status: bigint, metadataURI: string] & {dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint, platformFee: bigint, createdAt: bigint, deliveryDeadline: bigint, status: bigint, metadataURI: string }
  

  export interface EscrowVaultInterface extends Interface {
    getFunction(nameOrSignature: "BPS_DENOMINATOR" | "EXPRESS_PREMIUM_BPS" | "MAX_DEAL_DURATION" | "MIN_DEAL_AMOUNT" | "PLATFORM_FEE_BPS" | "acceptAdmin" | "accumulatedFees" | "admin" | "authorizedWorkflows" | "calculateFee" | "cancelDeal" | "claimExpiredDeal" | "confirmDeal" | "confirmDelivery" | "createDeal" | "deals" | "disputeResolver" | "expressSettle" | "feeCollector" | "getDeal" | "getDealStatus" | "markDisputed" | "markShipped" | "nextDealId" | "pendingAdmin" | "purchaseOrderContract" | "resolveDispute" | "setAuthorizedWorkflow" | "setDisputeResolver" | "setFeeCollector" | "setPurchaseOrderContract" | "transferAdmin" | "usdc" | "withdrawFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DealCancelled" | "DealConfirmed" | "DealCreated" | "DealDelivered" | "DealDisputed" | "DealRefunded" | "DealShipped" | "EscrowReleased" | "ExpressSettlement"): EventFragment;

    encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'EXPRESS_PREMIUM_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_DEAL_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_DEAL_AMOUNT', values?: undefined): string;
encodeFunctionData(functionFragment: 'PLATFORM_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedWorkflows', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'calculateFee', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimExpiredDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmDelivery', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createDeal', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'deals', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'disputeResolver', values?: undefined): string;
encodeFunctionData(functionFragment: 'expressSettle', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeCollector', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDeal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDealStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markDisputed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markShipped', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextDealId', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchaseOrderContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setAuthorizedWorkflow', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setDisputeResolver', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setFeeCollector', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setPurchaseOrderContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'EXPRESS_PREMIUM_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_DEAL_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_DEAL_AMOUNT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PLATFORM_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedWorkflows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateFee', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimExpiredDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeResolver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expressSettle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDeal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDealStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markDisputed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markShipped', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextDealId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchaseOrderContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedWorkflow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setDisputeResolver', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeCollector', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPurchaseOrderContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
  }

  
    export namespace DealCancelledEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealConfirmedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealCreatedEvent {
      export type InputTuple = [dealId: BigNumberish, agentId: BigNumberish, buyer: AddressLike, supplier: AddressLike, amount: BigNumberish];
      export type OutputTuple = [dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint];
      export interface OutputObject {dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealDeliveredEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealDisputedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealRefundedEvent {
      export type InputTuple = [dealId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [dealId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {dealId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealShippedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowReleasedEvent {
      export type InputTuple = [dealId: BigNumberish, supplier: AddressLike, supplierAmount: BigNumberish, feeAmount: BigNumberish];
      export type OutputTuple = [dealId: bigint, supplier: string, supplierAmount: bigint, feeAmount: bigint];
      export interface OutputObject {dealId: bigint, supplier: string, supplierAmount: bigint, feeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExpressSettlementEvent {
      export type InputTuple = [dealId: BigNumberish, premiumPaid: BigNumberish];
      export type OutputTuple = [dealId: bigint, premiumPaid: bigint];
      export interface OutputObject {dealId: bigint, premiumPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EscrowVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): EscrowVault;
    waitForDeployment(): Promise<this>;

    interface: EscrowVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    EXPRESS_PREMIUM_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_DEAL_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_DEAL_AMOUNT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PLATFORM_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptAdmin: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authorizedWorkflows: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    calculateFee: TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    cancelDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimExpiredDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmDelivery: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createDeal: TypedContractMethod<
      [agentId: BigNumberish, supplier: AddressLike, amount: BigNumberish, deliveryDeadline: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >
    

    
    deals: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint, bigint, bigint, string] & {dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint, platformFee: bigint, createdAt: bigint, deliveryDeadline: bigint, status: bigint, metadataURI: string }],
      'view'
    >
    

    
    disputeResolver: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    expressSettle: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    feeCollector: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getDeal: TypedContractMethod<
      [dealId: BigNumberish, ],
      [DealStructOutput],
      'view'
    >
    

    
    getDealStatus: TypedContractMethod<
      [dealId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    markDisputed: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    markShipped: TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextDealId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pendingAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    purchaseOrderContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    resolveDispute: TypedContractMethod<
      [dealId: BigNumberish, buyerRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setAuthorizedWorkflow: TypedContractMethod<
      [workflow: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setDisputeResolver: TypedContractMethod<
      [_resolver: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeCollector: TypedContractMethod<
      [_feeCollector: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setPurchaseOrderContract: TypedContractMethod<
      [_po: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'EXPRESS_PREMIUM_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_DEAL_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_DEAL_AMOUNT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PLATFORM_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptAdmin'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedWorkflows'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'calculateFee'): TypedContractMethod<
      [amount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimExpiredDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmDelivery'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createDeal'): TypedContractMethod<
      [agentId: BigNumberish, supplier: AddressLike, amount: BigNumberish, deliveryDeadline: BigNumberish, metadataURI: string, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deals'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, string, bigint, bigint, bigint, bigint, bigint, string] & {dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint, platformFee: bigint, createdAt: bigint, deliveryDeadline: bigint, status: bigint, metadataURI: string }],
      'view'
    >;
getFunction(nameOrSignature: 'disputeResolver'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'expressSettle'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeCollector'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDeal'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [DealStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getDealStatus'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'markDisputed'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'markShipped'): TypedContractMethod<
      [dealId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextDealId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'purchaseOrderContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [dealId: BigNumberish, buyerRefundBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthorizedWorkflow'): TypedContractMethod<
      [workflow: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setDisputeResolver'): TypedContractMethod<
      [_resolver: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeCollector'): TypedContractMethod<
      [_feeCollector: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPurchaseOrderContract'): TypedContractMethod<
      [_po: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DealCancelled'): TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
getEvent(key: 'DealConfirmed'): TypedContractEvent<DealConfirmedEvent.InputTuple, DealConfirmedEvent.OutputTuple, DealConfirmedEvent.OutputObject>;
getEvent(key: 'DealCreated'): TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
getEvent(key: 'DealDelivered'): TypedContractEvent<DealDeliveredEvent.InputTuple, DealDeliveredEvent.OutputTuple, DealDeliveredEvent.OutputObject>;
getEvent(key: 'DealDisputed'): TypedContractEvent<DealDisputedEvent.InputTuple, DealDisputedEvent.OutputTuple, DealDisputedEvent.OutputObject>;
getEvent(key: 'DealRefunded'): TypedContractEvent<DealRefundedEvent.InputTuple, DealRefundedEvent.OutputTuple, DealRefundedEvent.OutputObject>;
getEvent(key: 'DealShipped'): TypedContractEvent<DealShippedEvent.InputTuple, DealShippedEvent.OutputTuple, DealShippedEvent.OutputObject>;
getEvent(key: 'EscrowReleased'): TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
getEvent(key: 'ExpressSettlement'): TypedContractEvent<ExpressSettlementEvent.InputTuple, ExpressSettlementEvent.OutputTuple, ExpressSettlementEvent.OutputObject>;

    filters: {
      
      'DealCancelled(uint256)': TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
      DealCancelled: TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
    

      'DealConfirmed(uint256)': TypedContractEvent<DealConfirmedEvent.InputTuple, DealConfirmedEvent.OutputTuple, DealConfirmedEvent.OutputObject>;
      DealConfirmed: TypedContractEvent<DealConfirmedEvent.InputTuple, DealConfirmedEvent.OutputTuple, DealConfirmedEvent.OutputObject>;
    

      'DealCreated(uint256,uint256,address,address,uint256)': TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
      DealCreated: TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
    

      'DealDelivered(uint256)': TypedContractEvent<DealDeliveredEvent.InputTuple, DealDeliveredEvent.OutputTuple, DealDeliveredEvent.OutputObject>;
      DealDelivered: TypedContractEvent<DealDeliveredEvent.InputTuple, DealDeliveredEvent.OutputTuple, DealDeliveredEvent.OutputObject>;
    

      'DealDisputed(uint256)': TypedContractEvent<DealDisputedEvent.InputTuple, DealDisputedEvent.OutputTuple, DealDisputedEvent.OutputObject>;
      DealDisputed: TypedContractEvent<DealDisputedEvent.InputTuple, DealDisputedEvent.OutputTuple, DealDisputedEvent.OutputObject>;
    

      'DealRefunded(uint256,address,uint256)': TypedContractEvent<DealRefundedEvent.InputTuple, DealRefundedEvent.OutputTuple, DealRefundedEvent.OutputObject>;
      DealRefunded: TypedContractEvent<DealRefundedEvent.InputTuple, DealRefundedEvent.OutputTuple, DealRefundedEvent.OutputObject>;
    

      'DealShipped(uint256)': TypedContractEvent<DealShippedEvent.InputTuple, DealShippedEvent.OutputTuple, DealShippedEvent.OutputObject>;
      DealShipped: TypedContractEvent<DealShippedEvent.InputTuple, DealShippedEvent.OutputTuple, DealShippedEvent.OutputObject>;
    

      'EscrowReleased(uint256,address,uint256,uint256)': TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
      EscrowReleased: TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
    

      'ExpressSettlement(uint256,uint256)': TypedContractEvent<ExpressSettlementEvent.InputTuple, ExpressSettlementEvent.OutputTuple, ExpressSettlementEvent.OutputObject>;
      ExpressSettlement: TypedContractEvent<ExpressSettlementEvent.InputTuple, ExpressSettlementEvent.OutputTuple, ExpressSettlementEvent.OutputObject>;
    
    };
  }