/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'AgentRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.AgentRegistry__factory>
getContractFactory(name: 'DisputeResolver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DisputeResolver__factory>
getContractFactory(name: 'EscrowVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.EscrowVault__factory>
getContractFactory(name: 'PriceOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PriceOracle__factory>
getContractFactory(name: 'IERC721Receiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC721Receiver__factory>
getContractFactory(name: 'PurchaseOrder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PurchaseOrder__factory>
getContractFactory(name: 'IAgentRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IAgentRegistry__factory>
getContractFactory(name: 'IDisputeResolver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IDisputeResolver__factory>
getContractFactory(name: 'IEscrowVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IEscrowVault__factory>
getContractFactory(name: 'IPriceOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPriceOracle__factory>
getContractFactory(name: 'IPurchaseOrder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IPurchaseOrder__factory>
getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>

  getContractAt(name: 'AgentRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.AgentRegistry>
getContractAt(name: 'DisputeResolver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DisputeResolver>
getContractAt(name: 'EscrowVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.EscrowVault>
getContractAt(name: 'PriceOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PriceOracle>
getContractAt(name: 'IERC721Receiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC721Receiver>
getContractAt(name: 'PurchaseOrder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PurchaseOrder>
getContractAt(name: 'IAgentRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IAgentRegistry>
getContractAt(name: 'IDisputeResolver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IDisputeResolver>
getContractAt(name: 'IEscrowVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IEscrowVault>
getContractAt(name: 'IPriceOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPriceOracle>
getContractAt(name: 'IPurchaseOrder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IPurchaseOrder>
getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>

  deployContract(name: 'AgentRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry>
deployContract(name: 'DisputeResolver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DisputeResolver>
deployContract(name: 'EscrowVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EscrowVault>
deployContract(name: 'PriceOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PriceOracle>
deployContract(name: 'IERC721Receiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC721Receiver>
deployContract(name: 'PurchaseOrder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PurchaseOrder>
deployContract(name: 'IAgentRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgentRegistry>
deployContract(name: 'IDisputeResolver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDisputeResolver>
deployContract(name: 'IEscrowVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrowVault>
deployContract(name: 'IPriceOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPriceOracle>
deployContract(name: 'IPurchaseOrder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPurchaseOrder>
deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

  deployContract(name: 'AgentRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.AgentRegistry>
deployContract(name: 'DisputeResolver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DisputeResolver>
deployContract(name: 'EscrowVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.EscrowVault>
deployContract(name: 'PriceOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PriceOracle>
deployContract(name: 'IERC721Receiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC721Receiver>
deployContract(name: 'PurchaseOrder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PurchaseOrder>
deployContract(name: 'IAgentRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IAgentRegistry>
deployContract(name: 'IDisputeResolver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IDisputeResolver>
deployContract(name: 'IEscrowVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IEscrowVault>
deployContract(name: 'IPriceOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPriceOracle>
deployContract(name: 'IPurchaseOrder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IPurchaseOrder>
deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  