/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
    export type PriceEntryStruct = {productHash: BytesLike, unitPrice: BigNumberish, moq: BigNumberish, shippingCost: BigNumberish, supplierScore: BigNumberish, timestamp: BigNumberish, supplierRef: string}

    export type PriceEntryStructOutput = [productHash: string, unitPrice: bigint, moq: bigint, shippingCost: bigint, supplierScore: bigint, timestamp: bigint, supplierRef: string] & {productHash: string, unitPrice: bigint, moq: bigint, shippingCost: bigint, supplierScore: bigint, timestamp: bigint, supplierRef: string }
  

  export interface PriceOracleInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_STALENESS_THRESHOLD" | "MAX_ENTRIES_PER_PRODUCT" | "acceptAdmin" | "admin" | "authorizedUpdaters" | "batchUpdatePrices" | "computeProductHash" | "getBestPrice" | "getBestSupplier" | "getEntryCount" | "getPrice" | "getProductCount" | "isPriceFresh" | "knownProducts" | "lastUpdated" | "pendingAdmin" | "productExists" | "setAuthorizedUpdater" | "setStalenessThreshold" | "stalenessThreshold" | "transferAdmin" | "updatePrice"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PriceBatchUpdated" | "PriceUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_STALENESS_THRESHOLD', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_ENTRIES_PER_PRODUCT', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'admin', values?: undefined): string;
encodeFunctionData(functionFragment: 'authorizedUpdaters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'batchUpdatePrices', values: [BytesLike[], PriceEntryStruct[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'computeProductHash', values: [string]): string;
encodeFunctionData(functionFragment: 'getBestPrice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getBestSupplier', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getEntryCount', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getPrice', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getProductCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'isPriceFresh', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'knownProducts', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastUpdated', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'pendingAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'productExists', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'setAuthorizedUpdater', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setStalenessThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stalenessThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePrice', values: [BytesLike, PriceEntryStruct[]]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_STALENESS_THRESHOLD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_ENTRIES_PER_PRODUCT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'admin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedUpdaters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'batchUpdatePrices', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'computeProductHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBestSupplier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEntryCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPriceFresh', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'knownProducts', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastUpdated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'productExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthorizedUpdater', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setStalenessThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stalenessThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePrice', data: BytesLike): Result;
  }

  
    export namespace PriceBatchUpdatedEvent {
      export type InputTuple = [productHashes: BytesLike[], timestamp: BigNumberish];
      export type OutputTuple = [productHashes: string[], timestamp: bigint];
      export interface OutputObject {productHashes: string[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceUpdatedEvent {
      export type InputTuple = [productHash: BytesLike, unitPrice: BigNumberish, supplierScore: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [productHash: string, unitPrice: bigint, supplierScore: bigint, timestamp: bigint];
      export interface OutputObject {productHash: string, unitPrice: bigint, supplierScore: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PriceOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): PriceOracle;
    waitForDeployment(): Promise<this>;

    interface: PriceOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_STALENESS_THRESHOLD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_ENTRIES_PER_PRODUCT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptAdmin: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    admin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authorizedUpdaters: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    batchUpdatePrices: TypedContractMethod<
      [productHashes: BytesLike[], allEntries: PriceEntryStruct[], entryCounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    computeProductHash: TypedContractMethod<
      [productId: string, ],
      [string],
      'view'
    >
    

    
    getBestPrice: TypedContractMethod<
      [productHash: BytesLike, ],
      [PriceEntryStructOutput],
      'view'
    >
    

    
    getBestSupplier: TypedContractMethod<
      [productHash: BytesLike, ],
      [PriceEntryStructOutput],
      'view'
    >
    

    
    getEntryCount: TypedContractMethod<
      [productHash: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    getPrice: TypedContractMethod<
      [productHash: BytesLike, ],
      [[PriceEntryStructOutput[], bigint] & {entries: PriceEntryStructOutput[], timestamp: bigint }],
      'view'
    >
    

    
    getProductCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isPriceFresh: TypedContractMethod<
      [productHash: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    knownProducts: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    lastUpdated: TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    pendingAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    productExists: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    setAuthorizedUpdater: TypedContractMethod<
      [updater: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setStalenessThreshold: TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stalenessThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePrice: TypedContractMethod<
      [productHash: BytesLike, entries: PriceEntryStruct[], ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_STALENESS_THRESHOLD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_ENTRIES_PER_PRODUCT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptAdmin'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'admin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authorizedUpdaters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'batchUpdatePrices'): TypedContractMethod<
      [productHashes: BytesLike[], allEntries: PriceEntryStruct[], entryCounts: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'computeProductHash'): TypedContractMethod<
      [productId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBestPrice'): TypedContractMethod<
      [productHash: BytesLike, ],
      [PriceEntryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getBestSupplier'): TypedContractMethod<
      [productHash: BytesLike, ],
      [PriceEntryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getEntryCount'): TypedContractMethod<
      [productHash: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPrice'): TypedContractMethod<
      [productHash: BytesLike, ],
      [[PriceEntryStructOutput[], bigint] & {entries: PriceEntryStructOutput[], timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getProductCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isPriceFresh'): TypedContractMethod<
      [productHash: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'knownProducts'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastUpdated'): TypedContractMethod<
      [arg0: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'productExists'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setAuthorizedUpdater'): TypedContractMethod<
      [updater: AddressLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setStalenessThreshold'): TypedContractMethod<
      [_threshold: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stalenessThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePrice'): TypedContractMethod<
      [productHash: BytesLike, entries: PriceEntryStruct[], ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PriceBatchUpdated'): TypedContractEvent<PriceBatchUpdatedEvent.InputTuple, PriceBatchUpdatedEvent.OutputTuple, PriceBatchUpdatedEvent.OutputObject>;
getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;

    filters: {
      
      'PriceBatchUpdated(bytes32[],uint256)': TypedContractEvent<PriceBatchUpdatedEvent.InputTuple, PriceBatchUpdatedEvent.OutputTuple, PriceBatchUpdatedEvent.OutputObject>;
      PriceBatchUpdated: TypedContractEvent<PriceBatchUpdatedEvent.InputTuple, PriceBatchUpdatedEvent.OutputTuple, PriceBatchUpdatedEvent.OutputObject>;
    

      'PriceUpdated(bytes32,uint256,uint256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    
    };
  }