/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../common.js"
  

  export interface IAgentRegistryInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "AgentCreated" | "AgentDeactivated" | "AgentReactivated" | "AgentStatsUpdated" | "AgentUpdated"): EventFragment;

    

    
  }

  
    export namespace AgentCreatedEvent {
      export type InputTuple = [agentId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [agentId: bigint, owner: string];
      export interface OutputObject {agentId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentDeactivatedEvent {
      export type InputTuple = [agentId: BigNumberish];
      export type OutputTuple = [agentId: bigint];
      export interface OutputObject {agentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentReactivatedEvent {
      export type InputTuple = [agentId: BigNumberish];
      export type OutputTuple = [agentId: bigint];
      export interface OutputObject {agentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentStatsUpdatedEvent {
      export type InputTuple = [agentId: BigNumberish, totalDeals: BigNumberish, totalVolume: BigNumberish, successRate: BigNumberish];
      export type OutputTuple = [agentId: bigint, totalDeals: bigint, totalVolume: bigint, successRate: bigint];
      export interface OutputObject {agentId: bigint, totalDeals: bigint, totalVolume: bigint, successRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AgentUpdatedEvent {
      export type InputTuple = [agentId: BigNumberish];
      export type OutputTuple = [agentId: bigint];
      export interface OutputObject {agentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IAgentRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IAgentRegistry;
    waitForDeployment(): Promise<this>;

    interface: IAgentRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'AgentCreated'): TypedContractEvent<AgentCreatedEvent.InputTuple, AgentCreatedEvent.OutputTuple, AgentCreatedEvent.OutputObject>;
getEvent(key: 'AgentDeactivated'): TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
getEvent(key: 'AgentReactivated'): TypedContractEvent<AgentReactivatedEvent.InputTuple, AgentReactivatedEvent.OutputTuple, AgentReactivatedEvent.OutputObject>;
getEvent(key: 'AgentStatsUpdated'): TypedContractEvent<AgentStatsUpdatedEvent.InputTuple, AgentStatsUpdatedEvent.OutputTuple, AgentStatsUpdatedEvent.OutputObject>;
getEvent(key: 'AgentUpdated'): TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;

    filters: {
      
      'AgentCreated(uint256,address)': TypedContractEvent<AgentCreatedEvent.InputTuple, AgentCreatedEvent.OutputTuple, AgentCreatedEvent.OutputObject>;
      AgentCreated: TypedContractEvent<AgentCreatedEvent.InputTuple, AgentCreatedEvent.OutputTuple, AgentCreatedEvent.OutputObject>;
    

      'AgentDeactivated(uint256)': TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
      AgentDeactivated: TypedContractEvent<AgentDeactivatedEvent.InputTuple, AgentDeactivatedEvent.OutputTuple, AgentDeactivatedEvent.OutputObject>;
    

      'AgentReactivated(uint256)': TypedContractEvent<AgentReactivatedEvent.InputTuple, AgentReactivatedEvent.OutputTuple, AgentReactivatedEvent.OutputObject>;
      AgentReactivated: TypedContractEvent<AgentReactivatedEvent.InputTuple, AgentReactivatedEvent.OutputTuple, AgentReactivatedEvent.OutputObject>;
    

      'AgentStatsUpdated(uint256,uint256,uint256,uint256)': TypedContractEvent<AgentStatsUpdatedEvent.InputTuple, AgentStatsUpdatedEvent.OutputTuple, AgentStatsUpdatedEvent.OutputObject>;
      AgentStatsUpdated: TypedContractEvent<AgentStatsUpdatedEvent.InputTuple, AgentStatsUpdatedEvent.OutputTuple, AgentStatsUpdatedEvent.OutputObject>;
    

      'AgentUpdated(uint256)': TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
      AgentUpdated: TypedContractEvent<AgentUpdatedEvent.InputTuple, AgentUpdatedEvent.OutputTuple, AgentUpdatedEvent.OutputObject>;
    
    };
  }