/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../common.js"
  

  export interface IDisputeResolverInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "DisputeExpired" | "DisputeFeeRefunded" | "DisputeFiled" | "DisputeResolved" | "SupplierResponded"): EventFragment;

    

    
  }

  
    export namespace DisputeExpiredEvent {
      export type InputTuple = [disputeId: BigNumberish];
      export type OutputTuple = [disputeId: bigint];
      export interface OutputObject {disputeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeFeeRefundedEvent {
      export type InputTuple = [disputeId: BigNumberish, to: AddressLike];
      export type OutputTuple = [disputeId: bigint, to: string];
      export interface OutputObject {disputeId: bigint, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeFiledEvent {
      export type InputTuple = [disputeId: BigNumberish, dealId: BigNumberish, filedBy: AddressLike];
      export type OutputTuple = [disputeId: bigint, dealId: bigint, filedBy: string];
      export interface OutputObject {disputeId: bigint, dealId: bigint, filedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [disputeId: BigNumberish, outcome: BigNumberish, buyerRefundBps: BigNumberish];
      export type OutputTuple = [disputeId: bigint, outcome: bigint, buyerRefundBps: bigint];
      export interface OutputObject {disputeId: bigint, outcome: bigint, buyerRefundBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SupplierRespondedEvent {
      export type InputTuple = [disputeId: BigNumberish, response: string];
      export type OutputTuple = [disputeId: bigint, response: string];
      export interface OutputObject {disputeId: bigint, response: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IDisputeResolver extends BaseContract {
    
    connect(runner?: ContractRunner | null): IDisputeResolver;
    waitForDeployment(): Promise<this>;

    interface: IDisputeResolverInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'DisputeExpired'): TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
getEvent(key: 'DisputeFeeRefunded'): TypedContractEvent<DisputeFeeRefundedEvent.InputTuple, DisputeFeeRefundedEvent.OutputTuple, DisputeFeeRefundedEvent.OutputObject>;
getEvent(key: 'DisputeFiled'): TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'SupplierResponded'): TypedContractEvent<SupplierRespondedEvent.InputTuple, SupplierRespondedEvent.OutputTuple, SupplierRespondedEvent.OutputObject>;

    filters: {
      
      'DisputeExpired(uint256)': TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
      DisputeExpired: TypedContractEvent<DisputeExpiredEvent.InputTuple, DisputeExpiredEvent.OutputTuple, DisputeExpiredEvent.OutputObject>;
    

      'DisputeFeeRefunded(uint256,address)': TypedContractEvent<DisputeFeeRefundedEvent.InputTuple, DisputeFeeRefundedEvent.OutputTuple, DisputeFeeRefundedEvent.OutputObject>;
      DisputeFeeRefunded: TypedContractEvent<DisputeFeeRefundedEvent.InputTuple, DisputeFeeRefundedEvent.OutputTuple, DisputeFeeRefundedEvent.OutputObject>;
    

      'DisputeFiled(uint256,uint256,address)': TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
      DisputeFiled: TypedContractEvent<DisputeFiledEvent.InputTuple, DisputeFiledEvent.OutputTuple, DisputeFiledEvent.OutputObject>;
    

      'DisputeResolved(uint256,uint8,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'SupplierResponded(uint256,string)': TypedContractEvent<SupplierRespondedEvent.InputTuple, SupplierRespondedEvent.OutputTuple, SupplierRespondedEvent.OutputObject>;
      SupplierResponded: TypedContractEvent<SupplierRespondedEvent.InputTuple, SupplierRespondedEvent.OutputTuple, SupplierRespondedEvent.OutputObject>;
    
    };
  }