/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, FunctionFragment, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../common.js"
  

  export interface IEscrowVaultInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "DealCancelled" | "DealConfirmed" | "DealCreated" | "DealDelivered" | "DealDisputed" | "DealRefunded" | "DealShipped" | "EscrowReleased" | "ExpressSettlement"): EventFragment;

    

    
  }

  
    export namespace DealCancelledEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealConfirmedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealCreatedEvent {
      export type InputTuple = [dealId: BigNumberish, agentId: BigNumberish, buyer: AddressLike, supplier: AddressLike, amount: BigNumberish];
      export type OutputTuple = [dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint];
      export interface OutputObject {dealId: bigint, agentId: bigint, buyer: string, supplier: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealDeliveredEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealDisputedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealRefundedEvent {
      export type InputTuple = [dealId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [dealId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {dealId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DealShippedEvent {
      export type InputTuple = [dealId: BigNumberish];
      export type OutputTuple = [dealId: bigint];
      export interface OutputObject {dealId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowReleasedEvent {
      export type InputTuple = [dealId: BigNumberish, supplier: AddressLike, supplierAmount: BigNumberish, feeAmount: BigNumberish];
      export type OutputTuple = [dealId: bigint, supplier: string, supplierAmount: bigint, feeAmount: bigint];
      export interface OutputObject {dealId: bigint, supplier: string, supplierAmount: bigint, feeAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExpressSettlementEvent {
      export type InputTuple = [dealId: BigNumberish, premiumPaid: BigNumberish];
      export type OutputTuple = [dealId: bigint, premiumPaid: bigint];
      export interface OutputObject {dealId: bigint, premiumPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IEscrowVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): IEscrowVault;
    waitForDeployment(): Promise<this>;

    interface: IEscrowVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'DealCancelled'): TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
getEvent(key: 'DealConfirmed'): TypedContractEvent<DealConfirmedEvent.InputTuple, DealConfirmedEvent.OutputTuple, DealConfirmedEvent.OutputObject>;
getEvent(key: 'DealCreated'): TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
getEvent(key: 'DealDelivered'): TypedContractEvent<DealDeliveredEvent.InputTuple, DealDeliveredEvent.OutputTuple, DealDeliveredEvent.OutputObject>;
getEvent(key: 'DealDisputed'): TypedContractEvent<DealDisputedEvent.InputTuple, DealDisputedEvent.OutputTuple, DealDisputedEvent.OutputObject>;
getEvent(key: 'DealRefunded'): TypedContractEvent<DealRefundedEvent.InputTuple, DealRefundedEvent.OutputTuple, DealRefundedEvent.OutputObject>;
getEvent(key: 'DealShipped'): TypedContractEvent<DealShippedEvent.InputTuple, DealShippedEvent.OutputTuple, DealShippedEvent.OutputObject>;
getEvent(key: 'EscrowReleased'): TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
getEvent(key: 'ExpressSettlement'): TypedContractEvent<ExpressSettlementEvent.InputTuple, ExpressSettlementEvent.OutputTuple, ExpressSettlementEvent.OutputObject>;

    filters: {
      
      'DealCancelled(uint256)': TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
      DealCancelled: TypedContractEvent<DealCancelledEvent.InputTuple, DealCancelledEvent.OutputTuple, DealCancelledEvent.OutputObject>;
    

      'DealConfirmed(uint256)': TypedContractEvent<DealConfirmedEvent.InputTuple, DealConfirmedEvent.OutputTuple, DealConfirmedEvent.OutputObject>;
      DealConfirmed: TypedContractEvent<DealConfirmedEvent.InputTuple, DealConfirmedEvent.OutputTuple, DealConfirmedEvent.OutputObject>;
    

      'DealCreated(uint256,uint256,address,address,uint256)': TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
      DealCreated: TypedContractEvent<DealCreatedEvent.InputTuple, DealCreatedEvent.OutputTuple, DealCreatedEvent.OutputObject>;
    

      'DealDelivered(uint256)': TypedContractEvent<DealDeliveredEvent.InputTuple, DealDeliveredEvent.OutputTuple, DealDeliveredEvent.OutputObject>;
      DealDelivered: TypedContractEvent<DealDeliveredEvent.InputTuple, DealDeliveredEvent.OutputTuple, DealDeliveredEvent.OutputObject>;
    

      'DealDisputed(uint256)': TypedContractEvent<DealDisputedEvent.InputTuple, DealDisputedEvent.OutputTuple, DealDisputedEvent.OutputObject>;
      DealDisputed: TypedContractEvent<DealDisputedEvent.InputTuple, DealDisputedEvent.OutputTuple, DealDisputedEvent.OutputObject>;
    

      'DealRefunded(uint256,address,uint256)': TypedContractEvent<DealRefundedEvent.InputTuple, DealRefundedEvent.OutputTuple, DealRefundedEvent.OutputObject>;
      DealRefunded: TypedContractEvent<DealRefundedEvent.InputTuple, DealRefundedEvent.OutputTuple, DealRefundedEvent.OutputObject>;
    

      'DealShipped(uint256)': TypedContractEvent<DealShippedEvent.InputTuple, DealShippedEvent.OutputTuple, DealShippedEvent.OutputObject>;
      DealShipped: TypedContractEvent<DealShippedEvent.InputTuple, DealShippedEvent.OutputTuple, DealShippedEvent.OutputObject>;
    

      'EscrowReleased(uint256,address,uint256,uint256)': TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
      EscrowReleased: TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
    

      'ExpressSettlement(uint256,uint256)': TypedContractEvent<ExpressSettlementEvent.InputTuple, ExpressSettlementEvent.OutputTuple, ExpressSettlementEvent.OutputObject>;
      ExpressSettlement: TypedContractEvent<ExpressSettlementEvent.InputTuple, ExpressSettlementEvent.OutputTuple, ExpressSettlementEvent.OutputObject>;
    
    };
  }