/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener } from "../../common.js"
  

  export interface IPriceOracleInterface extends Interface {
    

    getEvent(nameOrSignatureOrTopic: "PriceBatchUpdated" | "PriceUpdated"): EventFragment;

    

    
  }

  
    export namespace PriceBatchUpdatedEvent {
      export type InputTuple = [productHashes: BytesLike[], timestamp: BigNumberish];
      export type OutputTuple = [productHashes: string[], timestamp: bigint];
      export interface OutputObject {productHashes: string[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceUpdatedEvent {
      export type InputTuple = [productHash: BytesLike, unitPrice: BigNumberish, supplierScore: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [productHash: string, unitPrice: bigint, supplierScore: bigint, timestamp: bigint];
      export interface OutputObject {productHash: string, unitPrice: bigint, supplierScore: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IPriceOracle extends BaseContract {
    
    connect(runner?: ContractRunner | null): IPriceOracle;
    waitForDeployment(): Promise<this>;

    interface: IPriceOracleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    

    getEvent(key: 'PriceBatchUpdated'): TypedContractEvent<PriceBatchUpdatedEvent.InputTuple, PriceBatchUpdatedEvent.OutputTuple, PriceBatchUpdatedEvent.OutputObject>;
getEvent(key: 'PriceUpdated'): TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;

    filters: {
      
      'PriceBatchUpdated(bytes32[],uint256)': TypedContractEvent<PriceBatchUpdatedEvent.InputTuple, PriceBatchUpdatedEvent.OutputTuple, PriceBatchUpdatedEvent.OutputObject>;
      PriceBatchUpdated: TypedContractEvent<PriceBatchUpdatedEvent.InputTuple, PriceBatchUpdatedEvent.OutputTuple, PriceBatchUpdatedEvent.OutputObject>;
    

      'PriceUpdated(bytes32,uint256,uint256,uint256)': TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
      PriceUpdated: TypedContractEvent<PriceUpdatedEvent.InputTuple, PriceUpdatedEvent.OutputTuple, PriceUpdatedEvent.OutputObject>;
    
    };
  }