/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IDisputeResolver, IDisputeResolverInterface } from "../../../interfaces/ISourcePilot.sol/IDisputeResolver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "dealId",
        "type": "uint256"
      }
    ],
    "name": "DisputeAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "DisputeNotFound",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "internalType": "enum DisputeStatus",
        "name": "current",
        "type": "uint8"
      }
    ],
    "name": "InvalidDisputeStatus",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InvalidRefundBps",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "NotDisputeParty",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "SupplierDeadlineNotReached",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      }
    ],
    "name": "DisputeExpired",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "DisputeFeeRefunded",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "dealId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "filedBy",
        "type": "address"
      }
    ],
    "name": "DisputeFiled",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum DisputeOutcome",
        "name": "outcome",
        "type": "uint8"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "buyerRefundBps",
        "type": "uint256"
      }
    ],
    "name": "DisputeResolved",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "disputeId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "response",
        "type": "string"
      }
    ],
    "name": "SupplierResponded",
    "type": "event"
  }
] as const;

  export class IDisputeResolver__factory {
    static readonly abi = _abi;
    static createInterface(): IDisputeResolverInterface {
      return new Interface(_abi) as IDisputeResolverInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IDisputeResolver {
      return new Contract(address, _abi, runner) as unknown as IDisputeResolver;
    }
  }
  