/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IPurchaseOrder, IPurchaseOrderInterface } from "../../../interfaces/ISourcePilot.sol/IPurchaseOrder.js";

  const _abi = [
  {
    "inputs": [],
    "name": "OnlyEscrow",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      }
    ],
    "name": "TokenNotFound",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "dealId",
        "type": "uint256"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "buyer",
        "type": "address"
      }
    ],
    "name": "PurchaseOrderMinted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "tokenId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "enum DealStatus",
        "name": "status",
        "type": "uint8"
      }
    ],
    "name": "PurchaseOrderStatusUpdated",
    "type": "event"
  }
] as const;

  export class IPurchaseOrder__factory {
    static readonly abi = _abi;
    static createInterface(): IPurchaseOrderInterface {
      return new Interface(_abi) as IPurchaseOrderInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IPurchaseOrder {
      return new Contract(address, _abi, runner) as unknown as IPurchaseOrder;
    }
  }
  